#pragma once

#define EXPECT_RGBAu_EQ(COL, R, G, B, A) { EXPECT_EQ(COL.r, R); EXPECT_EQ(COL.g, G); EXPECT_EQ(COL.b, B); EXPECT_EQ(COL.a, A); };
#define EXPECT_RGBu_EQ(COL, R, G, B) { EXPECT_EQ(COL.r, R); EXPECT_EQ(COL.g, G); EXPECT_EQ(COL.b, B); };
#define EXPECT_HSVu_EQ(COL, H, S, V) { EXPECT_EQ(COL.h, H); EXPECT_EQ(COL.s, S); EXPECT_EQ(COL.v, V); };

#define COL_VAL_TOLERANCE 0.00001

#define EXPECT_RGBAf_EQ(COL, R, G, B, A) { EXPECT_NEAR(COL.r, R, COL_VAL_TOLERANCE); EXPECT_NEAR(COL.g, G, COL_VAL_TOLERANCE); EXPECT_NEAR(COL.b, B, COL_VAL_TOLERANCE); EXPECT_NEAR(COL.a, A, COL_VAL_TOLERANCE); };
#define EXPECT_RGBf_EQ(COL, R, G, B) { EXPECT_NEAR(COL.r, R, COL_VAL_TOLERANCE); EXPECT_NEAR(COL.g, G, COL_VAL_TOLERANCE); EXPECT_NEAR(COL.b, B, COL_VAL_TOLERANCE); };
#define EXPECT_HSVf_EQ(COL, H, S, V) { EXPECT_NEAR(COL.h, H, COL_VAL_TOLERANCE); EXPECT_NEAR(COL.s, S, COL_VAL_TOLERANCE); EXPECT_NEAR(COL.v, V, COL_VAL_TOLERANCE); };
